### ISSUE TITLE
Cannot access to Aiursoft website

### ISSUE THREAD

**Issue by ranzeplay** [AiursoftWeb/Nexus#165]
![Annotation 2020-01-04 172530](https://user-images.githubusercontent.com/43675876/71763485-67c5f000-2f17-11ea-95bc-5f4313dd044c.png)
![Annotation 2020-01-04 172531](https://user-images.githubusercontent.com/43675876/71763486-67c5f000-2f17-11ea-85ba-633979f22a54.png)

No 500 error

**Comment by Anduin2017** [comment]
Sorry about that but our Azure subscription was disabled because of lack of money. we are trying to fix it as soon as possible.

**Comment by Anduin2017** [comment]
Sorry about that. We have changed our service provider and now all the data was migrated. Sorry for interruption again.
