### ISSUE TITLE
How to run locally? 

### ISSUE THREAD

**Issue by hitaspdotnet** [AiursoftWeb/Nexus#179]
Hi,
Without "How to run" step's we can't contribute.
Please update the docs.

**Comment by Anduin2017** [comment]
Yep. We are working on it.

However, currently running it is extremely difficult because it requires running at least 10+ ASP.NET Core services and config the connections between them. We have planed to make it easier and refactoring some basic communication layers.

Running locally document might be released in one or two months. Thanks for your feedback! 😊

**Comment by Anduin2017** [comment]
## How to install

### Brief steps

* Get a domain name. (Like aiur.io)
* Get a new server.
* Create DNS record.
* Execute the install command on your server.

### Get a server

Get a brand new Ubuntu 18.04 server.

* Server must be Ubuntu 18.04. (20.04 and 16.04 is not supported)
* Server must have a public IP address. (No local VM)
* Server must have access to the global Internet. (Not Chinese network)

Vultr or DigitalOcean is suggested. [Get it from Vultr](https://www.vultr.com/?ref=7274488).

### Install on server

Create a wildcard domian record to your server's IP.

> Example: Resolve *.aiur.io to 123.123.123.123

Execute the following command on the server (Replace the `instance.name` to your own brand name.):

```bash
$ curl -sL https://install.aiurs.co | sudo bash -s aiur.io instance.name
```

### Upgrade your server

If we release a newer version, and you can upgrade your server via:

```bash
$ curl -sL https://github.com/AiursoftWeb/Nexus/raw/master/upgrade.sh | sudo bash -s instance.name
```

**Comment by hitaspdotnet** [comment]
this is not local, but thanks!

**Comment by Anduin2017** [comment]
@hitaspdotnet Hi. To run the project locally has been simplified. Now you can run it really on your local machine.
