### ISSUE TITLE
Strange text appeared when view sign in page using Chinese

### ISSUE THREAD

**Issue by ranzeplay** [AiursoftWeb/Nexus#92]
When I let email and password sections as blank, it shows this.

The Aiursoft账户 field is required.
The 密码 field is required.

**Comment by Anduin2017** [comment]
Thanks. Will fix.

**Comment by Anduin2017** [comment]
![Annotation 2019-05-28 110745](https://user-images.githubusercontent.com/19531547/58447971-e0223280-8138-11e9-8f19-4c219751da87.jpg)

Fixed. Thanks for your feedback!
